name: cronjob
on : 
 schedule:
   - corn : '*/1 * * * *'

jobs:
  cron:
  runs-on  : ubuntu-latest

  steps:
   - uses : action/checkout@v4
     uses:  actions/setup-python@v5
     with:
         python-version: '3.13' 
     run: python hello.py

 