name: new git Action
on: push

jobs:
 newgitaction:
    runs-on: ubuntu-latest

    steps:
       steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v5
            with:
              python-version: '3.13' 
          - run: python hello.py